## Information ##
BC_INDEX_FPATH: '/stornext/General/data/user_managed/grpu_mritchie_1/Yue/preprocess/data/barcode7.tab'
BC_IDs_DEFAULT: '1-383'
BC_SEQ_COLUMN: 1
UMI_START_POSITION: 0
UMI_LENGTH: 6
BC_START_POSITION: 6
BC_LENGTH: 7

## Tools ##
## Alignment ##
ALIGNER: 'bowtie2'
BOWTIE2_INDEX_PREFIX: '/stornext/General/data/user_managed/grpu_mritchie_1/Yue/preprocess/celseq2/index/homo_bowtie_index'
BOWTIE2: 'bowtie2'

## Annotations ##
GFF: '/stornext/General/data/user_managed/grpu_mritchie_1/Yue/preprocess/data/homo_ercc.gtf'
FEATURE_ID: 'gene_id'
## What is the content of the "gene"? Mostly 'exon'.
FEATURE_CONTENT: 'exon'

## Demultiplexing ##
FASTQ_QUAL_MIN_OF_BC: 10
CUT_LENGTH: 35

## UMI Count ##
ALN_QUAL_MIN: 0

## Running Parameters ##
num_threads: 5
verbose: True

